### ISSUE TITLE
Reserved domain

### ISSUE THREAD

**Issue by jopenmolles** [casperboone/casperboone.com#1]
When I open casperboone.com I get the following message:
![image](https://user-images.githubusercontent.com/14317441/99404114-85ac0180-28eb-11eb-8273-4e9eb12c7a5a.png)

**Reproduction steps:**
- Go to casperboone.com in Chrome (Version 86.0.4240.198 64-bit)

Tested on Windows 10

**Comment by casperboone** [comment]
Hey Jop, thx for the report! The DNS changes are still being propagated I guess 😅 . I expect it to work in a couple of hours 😄.

**Comment by casperboone** [comment]
Fixed 😄
